### ISSUE TITLE
README: clarify that server-side KMS is supported

### ISSUE THREAD

**Issue by pda** [cultureamp/parameter-store-exec#1]
The description should probably mention that Parameter Store items can be KMS-encrypted; it's part of AWS Parameter Store not `parameter-store-exec`, but it's a strong selling point and non-obvious for people unfamiliar with Parameter Store.

Also, the example using `--type SecureString` should be explicit about KMS to help make this clear.

**Comment by ambsw-technology** [comment]
Probably safe to close this now.  Benefits of Parameter Store are well documented elsewhere.  Most people will find your package when searching for a way to leverage Parameter Store in their app.  If anything, expanding on the Prior Art section is more useful to that audience who need to understand the different approaches.
