### ISSUE TITLE
Want to use numbers for environement variables

### ISSUE THREAD

**Issue by tmitz** [cultureamp/parameter-store-exec#5]
parameter-store-exec will replace anything other than uppercase alphabets(A-Z).
But, there are cases where you wants to number. For example, when setting environment variables for S3.

```go
transformPattern = regexp.MustCompile("[^A-Z0-9_]")
```
How about a proposal to change `transformPattern` like the above code?

**Comment by pda** [comment]
Fixed in #6

**Comment by tmitz** [comment]
Thx! 😄
